name: CI/CD Pipeline for PersistenceCore

on:
  push:
    branches:
      - 'CI-branch-test'
    tags:
      - 'v*.*.*' # Trigger on version tags
  release:
    types:
      - created

env:
  IMAGE_NAME: 8857890900/persistencecore_test

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with Heighliner
        uses: strangelove-ventures/heighliner-build-action@v0.0.3
        with:
          image-name: ${{ env.IMAGE_NAME }}
          # Assuming the action can build and tag the image but not push
          platform: linux/amd64,linux/arm64
          chain: persistence
          git-ref: ${{ github.ref_name }}
          config-path: ./chains.yaml
          # Ensure the action outputs the name of the Docker image it built
          # This is a placeholder and may need to be adjusted
          output: image-name

      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_TAG="${{ github.event.release.tag_name || github.ref_name }}"
          docker push "${{ env.IMAGE_NAME }}:${IMAGE_TAG}"

  draft-release:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            New release of PersistenceCore ${{ github.ref_name }}.
            Docker images for amd64 and arm64 are now available on Docker Hub.

            `docker pull ${{ env.IMAGE_NAME }}:${{ github.ref_name }}`
