name: CI/CD Pipeline for PersistenceCore with Docker Hub and Release Drafting

on:
  push:
    branches:
      - 'CI-branch-test'
    tags:
      - 'v*.*.*' 
  release:
    types:
      - created

env:
  IMAGE_NAME: "8857890900/persistencecore_test"
  REGISTRY: "docker.io"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with configuration
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/persistencecore/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          push: true
          build-args: CONFIG_PATH=./chains.yaml

  draft-release:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            New release of PersistenceCore ${{ github.ref_name }}.
            Docker images for amd64 and arm64 are now available on Docker Hub.

            `docker pull ${{ env.IMAGE_NAME }}:${{ github.ref_name }}`
            
