name: CI/CD Pipeline for PersistenceCore

on:
  push:
    branches:
      - 'CI-branch-test'
    tags:
      - 'v*.*.*' # Trigger on version tags
  release:
    types:
      - created

env:
  IMAGE_NAME: "8857890900/persistencecore_test"
  REGISTRY: "docker.io"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with Heighliner
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/persistencecore/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          push: true
          platforms: linux/amd64,linux/arm64

  draft-release:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            New release of PersistenceCore ${{ github.ref_name }}.
            Docker images for amd64 and arm64 are now available on Docker Hub.

            `docker pull ${{ env.IMAGE_NAME }}:${{ github.ref_name }}`

            Attached are the architecture-specific binaries and SHA256 checksums for PersistenceCore.
          files: |
            ./persistenceCore_linux-amd64
            ./persistenceCore_linux-arm64
            ./persistenceCore_sha256.txt
